PROJECT_ID = "your project id"
VOICE_CLONE_PROJECT_ID = "your project id"
LOCATION = "us-central1"

AUTH_TYPE="SA"
SA_KEY_FILE_PATH = "your service account key file path"

# 存储桶,用于指定存储视频clip(call llm 使用)的bucket 
mc_bucket_name="your bucket name" 

# 存储桶下的目录
mc_object_prefix="movie-demo-part"

#用于指定视频分段时间
mc_partition_seconds = 600 

#如果使用minimax语音，请提供对应的groupid&key
minimax_group_id="your minimax group id"
minimax_api_key="your minimax key"